package com.example.musicplayer.utility

object Constants {
    const val audioExtension = "mp3 ogg wav"
    const val NOTIFICATION_INTENT = "NOTIFICATION_INTENT"
    const val NOTIFICATION_PLAYER_NEXT_INTENT = "NOTIFICATION_PLAYER_NEXT_INTENT"
    const val NOTIFICATION_PLAYER_BEFORE_INTENT = "NOTIFICATION_PLAYER_BEFORE_INTENT"
    const val NOTIFICATION_PLAY_INTENT = "NOTIFICATION_PLAY_INTENT"
    const val NOTIFICATION_PAUSE_INTENT = "NOTIFICATION_PAUSE_INTENT"
    const val AUDIO_FOCUS_CHANGED = "AUDIO_FOCUS_CHANGED"
}